name: Deploy Laravel App to Droplet

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend and frontend dependencies
        run: |
          composer install --no-progress --prefer-dist
          npm install

      - name: Build frontend assets with Vite
        run: npm run build

      - name: Upload .env file (optional, if you want it in GitHub Secrets)
        run: echo "${{ secrets.LARAVEL_ENV }}" > .env

      - name: Deploy codebase via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www
            if [ ! -d "reviewApp" ]; then
              git clone https://github.com/DavidArabuli/reviewsWebsite.git reviewApp
            fi
            cd reviewApp
            git fetch --all
            git reset --hard origin/production
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link || echo "Storage link already exists"

      - name: Upload Vite build assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "public/build"
          target: "/var/www/reviewApp/public"
